---

- name: Update apt-get repo and cache
  apt:
    update_cache: yes

- name: Add Docker's official GPG key
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add Docker PPA repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Update apt-get repo and cache
  apt:
    update_cache: yes

- name: Install docker packages
  apt:
    name: "{{ base_docker_packages }}"
    state: present

